package com.bangkit.jetbukuku.model

import com.bangkit.jetbukuku.R

object FakeBookDataSource {
    val dummyBooks = listOf(
        Book(1, R.drawable.book_1, "BUMI", "Tere Liye", "2014", "Namaku Raib, usiaku 15 tahun, kelas sepuluh. Aku anak perempuan seperti kalian, adik-adik kalian, tetangga kalian. Aku punya dua kucing, namanya si Putih dan si Hitam. Mama dan papaku menyenangkan. Guru-guru di sekolahku seru. Teman-temanku baik dan kompak. Aku sama seperti remaja kebanyakan, kecuali satu hal. Sesuatu yang kusimpan sendiri sejak kecil. Sesuatu yang menakjubkan. Namaku Raib. Dan aku bisa menghilang.", false),
        Book(2, R.drawable.book_2, "BINTANG", "Tere Liye", "2017", "Bintang adalah buku keempat dari serial Bumi yang ditulis oleh Tere Liye. Tere Liye ialah nama pena dari seorang penulis novel tersohor di Indonesia. Novel Bintang menceritakan tentang Raib, Seli, dan Ali, mereka adalah murid SMA kelas 11 dan berteman baik. Penampilan mereka sama seperti para murid SMA lainnya, tetapi siapa sangka bahwa mereka memiliki dan menyimpan banyak rahasia besar.", false),
        Book(3, R.drawable.book_3, "MATAHARI", "Tere Liye", "2016","Namanya Ali, 15 tahun, kelas X. Jika saja orangtuanya mengizinkan, seharusnya dia sudah duduk di tingkat akhir ilmu fisika program doktor di universitas ternama. Ali tidak menyukai sekolahnya, guru-gurunya, teman-teman sekelasnya. Semua membosankan baginya. Tapi sejak dia mengetahui ada yang aneh pada diriku dan Seli, teman sekelasnya, hidupnya yang membosankan berubah seru. Aku bisa menghilang, dan Seli bisa mengeluarkan petir. Ali sendiri punya rahasia kecil. Dia bisa berubah menjadi beruang raksasa. Kami bertiga kemudian bertualang ke tempat-tempat menakjubkan. Namanya Ali. Dia tahu sejak dulu dunia ini tidak sesederhana yang dilihat orang. Dan di atas segalanya, dia akhirnya tahu persahabatan adalah hal yang paling utama.", false),
        Book(4, R.drawable.book_4, "SELENA", "Tere Liye", "2020", " \"Selena\" dan \"Nebula\" adalah buku ke-8 dan ke-9 yang menceritakan siapa orangtua Raib dalam serial petualangan dunia paralel. Dua buku ini sebaiknya dibaca berurutan. Kedua buku ini juga bercerita tentang Akademi Bayangan Tingkat Tinggi, sekolah terbaik di \"Selena\" dan \"Nebula\" adalah buku ke-8 dan ke-9 yang menceritakan siapa orangtua Raib dalam serial petualangan dunia paralel. Dua buku ini sebaiknya dibaca berurutan. Kedua buku ini juga bercerita tentang Akademi Bayangan Tingkat Tinggi, sekolah terbaik di seluruh Klan Bulan.", false),
        Book(5, R.drawable.book_5, "LUMPU", "Tere Liye", "2021", "Yes! Akhirnya, Raib, Seli, dan Ali kembali bertualang. Kalian sudah kangen dengan trio ini? Misi mereka adalah menyelamatkan Miss Selena, guru matematika mereka. Tapi, apakah semua berjalan mudah? Siapa yang bersedia membantu mereka? Kali ini, si genius Ali memutuskan meminta bantuan dari sosok yang tidak terduga, karena musuh dari musuh adalah teman. Apakah Raib bisa melupakan masa lalu itu dengan memaafkan Miss Selena? Bagaimana dengan Tazk? Apakah Raib bisa bertemu lagi dengan ayahnya, atau itu masih menjadi misteri? Bagaimana dengan jejak ekspedisi Klan Aldebaran 40.000 tahun lalu? Benda apa saja yang ditinggalkan oleh perjalanan besar tersebut? Pertarungan panjang telah menunggu mereka. Dan lawan mereka adalah Lumpu, petarung yang memiliki teknik unik, yaitu melumpuhkan kekuatan lawan. Itu teknik yang amat menakutkan, karena Lumpu bisa menghabisi teknik bertarung. Jangan-jangan… Siapa di antara Raib, Seli, dan Ali yang akan kehilangan kekuatan di dunia paralel?", false),
        Book(6, R.drawable.book_6, "BULAN", "Tere Liye", "2015", "Petualangan Raib, Seli, dan Ali berlanjut.Beberapa bulan setelah peristiwa klan bulan, Miss Selena akhirnya muncul di sekolah. Ia membawa kabar menggembirakan untuk anak-anak yang berjiwa petualang seperti Raib, Seli, dan Ali. Miss Selena bersama dengan Av akan mengajak mereka untuk mengunjungi klan matahari selama dua minggu. Av berencana akan bertemu dengan ketua konsil klan matahari, yang menguasai klan matahari sepenuhnya untuk mencari sekutu dalam menghadapi Tamus yang diperkirakan akan bebas dan juga membebaskan raja tanpa mahkota.", false),
        Book(7, R.drawable.book_7, "SI ANAK PEMBERANI", "Tere Liye", "2019", "\"Aku Eliana, si anak pemberani, anak sulung Bapak dan Mamak yang akan menjadi pembela kebenaran dan keadilan. Berdiri paling gagah di depan membela orang-orang lemah dan teraniaya. Buku ini tentang Eliana, si anak pemberani yang membela tanah, sungai, hutan, dan lembah kampung halamannya. Saat kerakusan dunia datang, Eliana bersama teman karibnya bahu-membahu melakukan perlawanan. Dari puluhan buku Tere Liye, serial ini adalah mahkotanya.", false),
        Book(8, R.drawable.book_8, "SAGARAS", "Tere Liye", "2016", "Akhirnya. Siapa orang tua Ali dijawab di buku ini. Ali, bertahun-tahun, berusaha memecahkan misteri itu. Paib dan Seli tentu tidak akan membiarkan Ali sendirian, mereka sahabat sejati. Dan jangan lupakan, Batozar alias Master B, dengan segenap kalimat kasar, seolah tidak peduli, dia selalu siap membela. Tapi bagaimana jika misteri itu terhadang tembok kokoh SagaraSe? Dan mereka harus bertarung hidup-mati lima ronde melawan Ksatria SagaraS? Jangan khawatir, kalian akan tersenyum lebar (dan boleh jadi sambil menangis), saat tiba di halaman terakhir buku ini. Buku ini adalah buku ke-13 dari serial BUMI.", false),
        Book(9, R.drawable.book_9, "PERGI", "Tere Liye", "2018", "Sebuah kisah tentang menemukan tujuan, ke mana hendak pergi, melalui kenangan demi kenangan masa lalu, pertarungan hidup-mati, untuk memutuskan ke mana langkah kaki akan dibawa. 'Kehidupanmu ada di persimpangan berikutnya, Agam. Dulu kamu bertanya tentang defenisi pulang, dan kamu berhasil menemukannya, bahwa siapapun pasti akan pulang ke hakikat kehidupan. Kamu akhirnya pulang menjenguk pusara bapak mamakmu, berdamai dengan masa lalu yang menyakitkan.Tapi lebih dari itu, ada pertanyaan penting berikutnya yang menunggu dijawab. Pergi. Sejatinya, kemana kita akan pergi setelah tahu defenisi pulang tersebut? Apa yang harus dilakukan? Berangkat ke mana? Bersama siapa? Apa 'kendaraannya'? Dan kemana tujuannya? Apa sebenarnya tujuan hidup kita? itulah persimpangan hidupmu sekarang, Bujang. Menemukan jawaban tersebut. 'Kamu akan pergi kemana?, Nak.''", false),
        Book(10, R.drawable.book_10, "PULANG", "Tere Liye", "2013", "\"Sebuah kisah karya penulis negeri sendiri, dengan latar kisah negeri sendiri, yang layak dinikmati, \" ---Tribun Jabar\" Sebuah kisah tentang perjalanan pulang, melalui pertarungan demi pertarungan, kesedihan demi kesedihan, untuk memeluk erat semua kebencian dan rasa sakit. Pulang", false),
        Book(11, R.drawable.book_11, "SI ANAK PINTAR", "Tere Liye", "2018", "\"Kau bukan Pukat si anak yang pintar.... kau lebih dari itu, kau Pukat si anak yang genius. Buku ini tentang Pukat, si anak paling pintar dalam keluarga. Masa kecilnya dipenuhi petualangan seru dan kejadian kocak, serta jangan lupakan pertengkaran kakak dan adik-adiknya. Tapi apakah dia mampu menjawab teka-teki hebat itu, apakah harta karun paling berharga di kampung mereka? Dari puluhan buku Tere Liye, serial ini adalah mahkotanya.", false),
        Book(12, R.drawable.book_12, "PULANG-PERGI", "Tere Liye", "2021", "Ada jodoh yang ditemukan lewat tatapan pertama. Ada persahabatan yang diawali lewat sapa hangat. Bagaimana jika takdir bersama ternyata, diawali dengan pertarungan mematikan? Lantas semua cerita berkelindan dengan, pengejaran demi pengejaran mencari jawaban?", false),
        Book(13, R.drawable.book_13, "KOMET", "Tere Liye", "2018", "Buku ini berkisah tentang petualangan tiga sahabat. Raib bisa menghilang. Seli bisa mengeluarkan petir. Dan Ali bisa melakukan apa saja. Buku ini juga berkisah tentang persahabatan yang mengharukan, pengorbanan yang tulus, keberanian, dan selalu berbuat baik. Karena sejatinya, itulah kekuatan terbesar di dunia paralel.", false),
        Book(14, R.drawable.book_14, "TENTANG KAMU", "Tere Liye", "2016", "Cerita dalam novel ini berfokus pada Sri Ningsih. Seorang perempuan dengan hati yang tulus, pekerja keras, sabar, dan penyayang. Namun Sri Ningsih tidak menceritakan perjalanan hidupnya sendiri. Kisahnya diulik oleh Zaman Zulkarnaen dari satu orang ke orang lain. Menggabungkan berbagai puzzle yang masih acak-acakan. Secara umum, Zaman hanya sebagai pion untuk menceritakan tangguhnya seorang Sri Ningsih.", false),
        Book(15, R.drawable.book_15, "DAUN YANG JATUH TAK PERNAH MEMBENCI ANGIN", "Tere Liye", "2010", "Dia bagai malaikat bagi keluarga kami. Merengkuh aku, adikku, dan Ibu dari kehidupan jalanan yang miskin dan nestapa. Memberikan makan, tempat berteduh, sekolah, dan janji masa depan yang lebih baik. Dia sungguh bagai malaikat bagi keluarga kami. Memberikan kasih sayang, perhatian, dan teladan tanpa mengharap budi sekali pun. Dan lihatlah, aku membalas itu semua dengan membiarkan mekar perasaan ini. Ibu benar, tak layak aku mencintai malaikat keluarga kami. Tak pantas. Maafkan aku, Ibu. Perasaan kagum, terpesona, atau entahlah itu muncul tak tertahankan bahkan sejak rambutku masih dikepang dua. Sekarang, ketika aku tahu dia boleh jadi tidak pernah menganggapku lebih dari seorang adik yang tidak tahu diri, biarlah... Biarlah aku luruh ke bumi seperti sehelai daun… daun yang tidak pernah membenci angin meski harus terenggutkan dari tangkai pohonnya.", false),
    )
}